@startuml

class Student {
    + m_name: std::string
    + Student(_name: std::string)
    ~ Student() 
    + print_name(): void
}

' note top of Student : Student.\nTODO: implements Kalman filter,\nmean filter ready,\nnormal data generate by random values
@enduml